
language: cpp
compiler:
  - gcc
  - clang

language: python
python:
  - "2.7"




# Setting up pre-requirements
before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - #sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - git clone https://github.com/BlockWorksCo/Platform.git
  - export BLOCKWORKS_PLATFORM_BASE=`pwd`/Platform


# Change this to your needs
script: 
  - export BLOCKWORKS_PLATFORM_BASE=`pwd`/Platform
  - cd IPStack/Tests && nosetests Tests.py




