


INCLUDES=-I$(ROCKETBLOX)/UART -I$(ROCKETBLOX)/Debug -I$(ROCKETBLOX)/GPIO -I$(ROCKETBLOX)/SimpleConsole -I$(ROCKETBLOX)/Storage
INCLUDES+=-I$(ROCKETBLOX)/Common
INCLUDES+=-I$(PLATFORM)

OBJS=\
AppMain.o \
PlatformMain.o 


include $(ROCKETBLOX)/Platform/$(PLATFORM)/Makefile





